[package]
name = "plaatbook"
version = "0.1.0"
authors = ["PlaatSoft <info@plaatsoft.nl>"]
edition = "2021"
license = "MIT"

[dependencies]
http = { git = "https://github.com/bplaat/crates.git", features = ["json"] }
router = { git = "https://github.com/bplaat/crates.git" }
sqlite = { git = "https://github.com/bplaat/crates.git", features = [
    "derive",
    "uuid",
    "chrono",
] }
uuid = { git = "https://github.com/bplaat/crates.git", features = [
    "v7",
    "serde",
] }
validate = { git = "https://github.com/bplaat/crates.git", features = [
    "derive",
    "email",
    "serde",
] }

chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7.1"
bcrypt = "0.16.0"
woothee = "0.13.0"
getrandom = "0.2.15"
base64 = "0.22.1"

[profile.release]
opt-level = "z"
strip = "symbols"
lto = "thin"
panic = "abort"
overflow-checks = false
