[package]
name = "plaatbook"
version = "0.1.0"
authors = ["PlaatSoft <info@plaatsoft.nl>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"
axum = { version = "0.7.9", default-features = false, features = [
    "tokio",
    "http1",
    "json",
] }
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.8.2", default-features = false, features = [
    "runtime-tokio",
    "macros",
    "sqlite",
    "uuid",
    "chrono",
] }
tokio = { version = "1.41", default-features = false, features = [
    "macros",
    "rt-multi-thread",
] }
tower-http = { version = "0.6.2", default-features = false, features = [
    "cors",
] }
uuid = { version = "1.11", features = ["serde", "v7"] }

[profile.release]
opt-level = "z"
strip = "symbols"
lto = "thin"
panic = "abort"
overflow-checks = false
