[package]
name = "plaatbook"
version = "0.1.0"
authors = ["PlaatSoft <info@plaatsoft.nl>"]
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4.38", features = ["serde"] }
http = { git = "https://github.com/bplaat/crates.git", features = ["json"] }
router = { git = "https://github.com/bplaat/crates.git" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlite = { git = "https://github.com/bplaat/crates.git", features = [
    "derive",
    "uuid",
    "chrono",
] }
uuid = { version = "1.11", features = ["serde", "v7"] }

[profile.release]
opt-level = "z"
strip = "symbols"
lto = "thin"
panic = "abort"
overflow-checks = false
