name: server
run-name: ${{ github.actor }} is checking server

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/server.yml"
      - "server/**"
  pull_request:
    paths:
      - ".github/workflows/server.yml"
      - "server/**"

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev
      - run: rustup toolchain add nightly --component rustfmt
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny,cargo-nextest
      - run: (cd server && PROFILE=ci ./meta.sh check)
      - uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          check_name: Rust Tests
          report_paths: server/target/nextest/ci/junit.xml
          require_tests: true
