name: server
run-name: ${{ github.actor }} is checking server

on:
  push:
    branches:
      - master
    paths:
      - "server/**"
  pull_request:
    paths:
      - "server/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-udeps,cargo-deny
      - run: make -C server ci
