name: web
run-name: ${{ github.actor }} is checking web

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/web.yml"
      - "web/**"
  pull_request:
    paths:
      - ".github/workflows/web.yml"
      - "web/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo install --git https://github.com/bplaat/crates.git openapi-generator
      - run: make -C web check
